#!/bin/bash

set -e

cd $(dirname $0)/..
PATH=$(pwd)/build-tools/bin:$PATH

. ./scripts/common-vars

build_projects()
{
    for project in "${BUILD_PROJECTS[@]}"; do
        echo "checking... ${project}"
        cd ${PROJECT_MAP["${project}_WORK_DIR"]}

        if [[ "$(< .rebuild)" == "true" ]] || [[ -f .manual ]]; then
            echo "building.. ${project}"
            wrap build
            if [ ${PROJECT_MAP["${project}_PACKAGE"]} == "true" ]; then
                wrap package
            fi
        fi

        cd ..
    done
}

build_projects
