#!/bin/bash

cd $(dirname $0)/..
PATH=$(pwd)/build-tools/bin:$PATH

. ./scripts/common-vars

build_projects()
{
    for project in "${PROJECTS[@]}"; do
        echo "checking... ${project}"
        cd ${PROJECT_MAP["${project}_WORK_DIR"]}

        need_to_build=$(cat .rebuild)
        if [[ "$(< .rebuild)" == "true" ]]; then
            echo "building.. ${project}"
            wrap build
        fi

        cd ..
    done
}

build_projects
