#!/bin/bash

set -e

cd $(dirname $0)/..

. ./scripts/common-vars

export PATH=$PATH:$(pwd)/build-tools/bin

clone_repo()
{
    git clone ${1}
}

notify()
{
    COMMIT=$(git rev-parse HEAD)
    TAG=$(git tag -l | sort -V | tail -1)

    REPO=$(git remote -v|grep origin |tail -1|sed -e 's/\(^[a-z].*github.com\)//' -e 's/^://' -e 's/^\///' |sed -e 's/\.git.*$//')
    BRANCH=$(git branch -q|grep '^\*'|cut -d' ' -f2)

    MESSAGE="Rancher IO Latest is now running: ${REPO} at commit: ${COMMIT} on Branch: ${BRANCH}."

    if [ "$(git rev-parse ${TAG})" == "${COMMIT}" ]; then
        MESSAGE="${MESSAGE} This is the latest released version\n"
    else
        MESSAGE="${MESSAGE} <https://github.com/${REPO}/compare/${TAG}...${COMMIT}| Details Here>"
    fi

    MESSAGE="${MESSAGE}" ../scripts/slack-notification
}

refresh_repos()
{
    local head_pre
    local head_post

    git checkout ${1}
    head_pre=$(git rev-parse HEAD)
    git pull -r 
    git reset --hard HEAD
    git clean -dxf
    head_post=$(git rev-parse HEAD)

    if [ "${head_pre}" != "${head_post}" ]; then
            echo "true" > .rebuild
    else
            echo "false" > .rebuild
    fi

    notify
}

main()
{
    local project 
    local head_pre
    local head_post
    local work_dir

    for project in "${GIT_PROJECTS[@]}"; do

        work_dir="${PROJECT_MAP[${project}_WORK_DIR]}"
        echo "Refreshing... ${project}"

        # Clone the repo if it doesn't exist.. else refresh
        if [ ! -d "./${work_dir}" ]; then
            clone_repo "${PROJECT_MAP[${project}_REPO]}" 
            echo "true" > ${work_dir}/.rebuild
            cd ./${work_dir}
            git checkout ${PROJECT_MAP[${project}_COMMIT]}
            notify
            cd ..
        else
            cd ./${work_dir}
            if [ ! -f .manual ]; then
                refresh_repos ${PROJECT_MAP[${project}_COMMIT]}
            fi
            cd ..
        fi
     done
}

cd $(dirname $0)/..

main
