#!/bin/bash

set -e

cd $(dirname $0)/..

. ./scripts/common-vars

export PATH=$PATH:$(pwd)/build-tools/bin

clone_repo()
{
    git clone ${1}
}

refresh_repos()
{
    local head_pre
    local head_post

    git checkout ${1}
    head_pre=$(git rev-parse HEAD)
    git pull -r 
    head_post=$(git rev-parse HEAD)

    if [ "${head_pre}" != "${head_post}" ]; then
            echo "true" > .rebuild
    else
            echo "false" > .rebuild
    fi
}

main()
{
    local project 
    local head_pre
    local head_post
    local work_dir

    for project in "${PROJECTS[@]}"; do

        work_dir="${PROJECT_MAP[${project}_WORK_DIR]}"
        echo "Refreshing... ${project}"

        # Clone the repo if it doesn't exist.. else refresh
        if [ ! -d "./${work_dir}" ]; then
            clone_repo "${PROJECT_MAP[${project}_REPO]}" 
            echo "true" > ${work_dir}/.rebuild
            cd ./${work_dir}
            git checkout ${PROJECT_MAP[${project}_COMMIT]}
            cd ..
        else
            cd ./${work_dir}
            if [ ! -f .manual ]; then
                refresh_repos ${PROJECT_MAP[${project}_COMMIT]}
            fi
            cd ..
        fi

     done
}

cd $(dirname $0)/..

main
