#!/bin/bash

if [ -z $SLACK_WEBHOOK_TOKEN ]; then
    echo "Need a webhook token..." 2>&1
    exit 0
fi


curl -X POST https://hooks.slack.com/services/${SLACK_WEBHOOK_TOKEN} -d "{
    \"text\": \"Rancherio ${REPO} is now running: ${COMMIT} on Branch ${BRANCH}. See Differences here: <https://github.com/${REPO}/compare/${TAG}...${COMMIT}| HERE>\"}"
