#!/bin/bash

: ${CATTLE_TEST_URL:="http://latest.rancher.io:8080"}
: ${PHANTOMJS_WEBDRIVER_PORT:-4444}
: ${API_AUTH_GITHUB_TEST_USER:-$API_AUTH_GITHUB_TEST_USER}
: ${API_AUTH_GITHUB_TEST_PASS:-$API_AUTH_GITHUB_TEST_PASS}
: ${API_AUTH_GITHUB_CLIENT_ID:-$API_AUTH_GITHUB_CLIENT_ID}
: ${API_AUTH_GITHUB_CLIENT_SECRET:-$API_AUTH_GITHUB_CLIENT_SECRET}
: ${API_AUTH_RANCHER_TEST_PASS:-$API_AUTH_RANCHER_TEST_PASS}

export CATTLE_TEST_URL PHANTOMJS_WEBDRIVER_PORT
export API_AUTH_GITHUB_TEST_USER API_AUTH_GITHUB_TEST_PASS
export API_AUTH_GITHUB_CLIENT_ID API_AUTH_RANCHER_TEST_PASS API_AUTH_GITHUB_CLIENT_SECRET

cd $(dirname $0)/..

wrapdocker

notify()
{
    MESSAGE=${1} ../scripts/slack-notification 
}

notify_alert()
{
    message="@channel: ${1}"
    MESSAGE=${message} ../scripts/slack-notification
}

bootstrap_validation_tests()
{
    cd validation-tests
    docker build --rm -t validation-test-container .
    cd ..
}


run_tests() 
{
    cd validation-tests
    notify "Starting Test Run..."
    docker run -e "CATTLE_TEST_URL=${CATTLE_TEST_URL}" \
        -e "PHANTOMJS_WEBDRIVER_PORT=${PHATOMJS_WEBDRIVER_PORT}" \
        -e "API_AUTH_GITHUB_TEST_USER=${API_AUTH_GITHUB_TEST_USER}" \
        -e "API_AUTH_GITHUB_TEST_PASS=${API_AUTH_GITHUB_TEST_PASS}" \
        -e "API_AUTH_GITHUB_CLIENT_ID=${API_AUTH_GITHUB_CLIENT_ID}" \
        -e "API_AUTH_RANCHER_TEST_PASS=${API_AUTH_RANCHER_TEST_PASS}" \
        -e "API_AUTH_GITHUB_CLIENT_SECRET=${API_AUTH_GITHUB_CLIENT_SECRET}" \
        -v $(pwd):/source \
        validation-test-container ./scripts/test
    if [ "$?" -eq "0" ]; then
        notify "Tests all Passed"
    else
        notify_alert "Rancher Latest Had Validation Test Failures!!!!"
    fi
}

wait_a_bit()
{
    echo -n "."
    sleep 6
}

echo -n "Checking for ${CATTLE_TEST_URL} to become available "
for ((i=0;i<300;i++))
do
    if [[ "$(curl -s ${CATTLE_TEST_URL}/ping)" = "pong" ]]; then
    	host_count=$(curl -s ${CATTLE_TEST_URL}/v1/hosts|python -mjson.tool|grep '"id"'|grep "1h.*"|wc -l)
	    if [ "$host_count" -ge "3" ]; then
            echo "OK"
            break
        else
	        wait_a_bit
        fi
    else
        wait_a_bit
    fi

    ### If we don't get a response after 30 mins... give up.
    if [ "$i" -eq "299" ]; then
        echo "Failed to reach environment" 1>&2
        notify_alert "Rancher latest environment failed to respond... no tests run."
        exit 1
    fi
done

bootstrap_validation_tests
run_tests
